### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by sandman18** [probablykasper/date-picker-svelte#14]
Hello,

Thanks for a great component!

I'm trying to change --sc-theme-calendar-maxWidth: 100vw;
to: --sc-theme-calendar-maxWidth: 80vw;

I can't seem to figure out where to place this to take over the css variable.

Any help would be great.

Thanks Again.

**Comment by probablykasper** [comment]
There's no supported CSS variable called `--sc-theme-calendar-maxWidth`. You can see the supported ones in the docs: https://date-picker-svelte.kasper.space/docs

**Comment by sandman18** [comment]
Okay, thanks.  Is there a best way to control the height and width?  It seems like it is always tied to the Viewport whereas I need it tied to a container.

**Comment by probablykasper** [comment]
It's not really tied to the viewport, everything is sized with `rem` or `px`. To change the size, you would have to resize it manually using `:global()`. The CSS is pretty straightforward, so it shouldn't be too hard to change stuff.

The width is already responsive to the `.date-time-picker` container, but to make the height responsive, this should work:
```css
:global(.date-time-picker .tab-container) {
  height: 100%;
  display: flex;
  flex-direction: column;
}
:global(.date-time-picker .week) {
  flex-grow: 1;
}
:global(.date-time-picker .cell) {
  height: 100%;
}
```

Then you can set both the width and height like this:
```css
:global(.date-time-picker) {
  box-sizing: border-box;
  width: 100%;
  height: 100%;
}
```

**Comment by Gildedter** [comment]
any chance for removing the `DateInput` border entirely? I'm wrapping in on a div and want that to dictate the border style, but can't seem to override it even with `!important`.

**Comment by probablykasper** [comment]
You just need to select the `input` element and disable the border on it, nothing special there really
```css
.my-parent-div :global(.date-time-field input) {
  border: none;
}
```
